//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Repositories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebClient.Repositories.QueryResource", typeof(QueryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_ACCOUNT.ChangePassword.
        /// </summary>
        internal static string Account_ChangePassword {
            get {
                return ResourceManager.GetString("Account_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_ACCOUNT.GETACCOUNTBYCODE.
        /// </summary>
        internal static string Account_GetAccountByCode {
            get {
                return ResourceManager.GetString("Account_GetAccountByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_ACCOUNT.GETACCOUNTBYUSERNAME.
        /// </summary>
        internal static string Account_GetAccountByUsername {
            get {
                return ResourceManager.GetString("Account_GetAccountByUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_ACCOUNT.GETACCOUNTSBYEMPLOYEEID.
        /// </summary>
        internal static string Account_GetAccountsByEmployeeId {
            get {
                return ResourceManager.GetString("Account_GetAccountsByEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_ACCOUNT.GETALLACCOUNTSBYEMPLOYEEID.
        /// </summary>
        internal static string Account_GetAllAccountsByEmployeeId {
            get {
                return ResourceManager.GetString("Account_GetAllAccountsByEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_ACCOUNT.LOGIN.
        /// </summary>
        internal static string ACCOUNT_LOGIN {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_NHANVIEN_QUYEN.GET_PERMISSIONIDS_OF_USER.
        /// </summary>
        internal static string AccPermission_GetPermissionIdsUser {
            get {
                return ResourceManager.GetString("AccPermission_GetPermissionIdsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_NHANVIEN_QUYEN.SET_PERMISSIONS.
        /// </summary>
        internal static string AccPermission_SetPermissions {
            get {
                return ResourceManager.GetString("AccPermission_SetPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_BIENLAI.ADJUST_AMOUNT.
        /// </summary>
        internal static string Adjust_Amount_Invoice {
            get {
                return ResourceManager.GetString("Adjust_Amount_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_CUSTOMER.GENERATENEWCUSTOMERCODE.
        /// </summary>
        internal static string Customer_GenerateNewCustomerCode {
            get {
                return ResourceManager.GetString("Customer_GenerateNewCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_DONVI.DELETE_DONVI.
        /// </summary>
        internal static string Department_Delete {
            get {
                return ResourceManager.GetString("Department_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_DONVI.GET_BY_ID.
        /// </summary>
        internal static string Department_Get_By_Id {
            get {
                return ResourceManager.GetString("Department_Get_By_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_DONVI.GET_ALL.
        /// </summary>
        internal static string Department_GetALL {
            get {
                return ResourceManager.GetString("Department_GetALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_DONVI.GETALLCHILDDEPARTMENTS.
        /// </summary>
        internal static string Department_GetAllChildDepartments {
            get {
                return ResourceManager.GetString("Department_GetAllChildDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_DONVI.GETCONTROLLEDDEPARTMENTS.
        /// </summary>
        internal static string Department_GetControlledDepartments {
            get {
                return ResourceManager.GetString("Department_GetControlledDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_DONVI.GETDEPARTMENTS.
        /// </summary>
        internal static string Department_GetDepartments {
            get {
                return ResourceManager.GetString("Department_GetDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_DONVI.GET_DEPARTMENTS_WITH_TERM.
        /// </summary>
        internal static string Department_GetDepartmentsWithTerm {
            get {
                return ResourceManager.GetString("Department_GetDepartmentsWithTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_DONVI.INSERT_UNIT.
        /// </summary>
        internal static string Department_Insert {
            get {
                return ResourceManager.GetString("Department_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_DONVI.UPDATE_UNIT.
        /// </summary>
        internal static string Department_Update {
            get {
                return ResourceManager.GetString("Department_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_DONVI.UpdateEmail.
        /// </summary>
        internal static string Department_UpdateEmail {
            get {
                return ResourceManager.GetString("Department_UpdateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_EMPLOYEE.DELETE_EMPLOYEE.
        /// </summary>
        internal static string Employee_DeleteById {
            get {
                return ResourceManager.GetString("Employee_DeleteById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_EMPLOYEE.GET_ALL_EMPLOYEE.
        /// </summary>
        internal static string Employee_Get_ALL {
            get {
                return ResourceManager.GetString("Employee_Get_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDLT_EMPLOYEE.GET_EMPLOYEE_BY_DEPARTMENT_ID.
        /// </summary>
        internal static string Employee_Get_By_Department_Id {
            get {
                return ResourceManager.GetString("Employee_Get_By_Department_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_EMPLOYEE.GET_EMPLOYEE_BY_ID.
        /// </summary>
        internal static string Employee_Get_By_Id {
            get {
                return ResourceManager.GetString("Employee_Get_By_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_EMPLOYEE.INSERT_EMPLOYEE.
        /// </summary>
        internal static string Employee_Insert {
            get {
                return ResourceManager.GetString("Employee_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_EMPLOYEE.UPDATE_EMPLOYEE.
        /// </summary>
        internal static string Employee_Update {
            get {
                return ResourceManager.GetString("Employee_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.ADD_FEATURE.
        /// </summary>
        internal static string Feature_AddFeature {
            get {
                return ResourceManager.GetString("Feature_AddFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.FEATURE_NOTPERMISSION_ACCOUNT.
        /// </summary>
        internal static string Feature_FeatureNoPermissionAccount {
            get {
                return ResourceManager.GetString("Feature_FeatureNoPermissionAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.FEATURE_PERMISSION_ACCOUNT.
        /// </summary>
        internal static string Feature_FeaturePermissionAccount {
            get {
                return ResourceManager.GetString("Feature_FeaturePermissionAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.GET_MENU_FEATURES.
        /// </summary>
        internal static string Feature_Get_Menu_Feature {
            get {
                return ResourceManager.GetString("Feature_Get_Menu_Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.GET_ALL.
        /// </summary>
        internal static string Feature_GetAll {
            get {
                return ResourceManager.GetString("Feature_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.IS_ACCESSED_FEATURE.
        /// </summary>
        internal static string Feature_IsAccessedFeature {
            get {
                return ResourceManager.GetString("Feature_IsAccessedFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.UPDATE_FEATURE.
        /// </summary>
        internal static string Feature_UpdateFeature {
            get {
                return ResourceManager.GetString("Feature_UpdateFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_FEE.DELETE_FEE.
        /// </summary>
        internal static string FEE_DELETE_BY_IDFEE {
            get {
                return ResourceManager.GetString("FEE_DELETE_BY_IDFEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_FEE.GET_FEE_BY_DEPART_ID_FOR_TABLE.
        /// </summary>
        internal static string FEE_GET_BY_DEPART_ID_FOR_TABLE {
            get {
                return ResourceManager.GetString("FEE_GET_BY_DEPART_ID_FOR_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_FEE.GET_FEE_BY_ID.
        /// </summary>
        internal static string FEE_GET_BY_IDFEE {
            get {
                return ResourceManager.GetString("FEE_GET_BY_IDFEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_FEE.INSERT_FEE.
        /// </summary>
        internal static string FEE_INSERT {
            get {
                return ResourceManager.GetString("FEE_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_FEE.UPDATE_FEE.
        /// </summary>
        internal static string FEE_UPDATE {
            get {
                return ResourceManager.GetString("FEE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_GROUPCUSTOMER.GetListByDepartmentId.
        /// </summary>
        internal static string GroupCustomer_GetListByDepartmentId {
            get {
                return ResourceManager.GetString("GroupCustomer_GetListByDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_BIENLAI.BASIC_BY_PARENTID.
        /// </summary>
        internal static string Invoice_Basic_By_ParentId {
            get {
                return ResourceManager.GetString("Invoice_Basic_By_ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_BIENLAI.DELETE_INDT_BY_INVOICEID.
        /// </summary>
        internal static string Invoice_DeleteInvoiceDetailsByInvoiceId {
            get {
                return ResourceManager.GetString("Invoice_DeleteInvoiceDetailsByInvoiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_BIENLAI.GENERATE_NEW_KEY_INVOICE.
        /// </summary>
        internal static string Invoice_GenerateNewInvoiceKey {
            get {
                return ResourceManager.GetString("Invoice_GenerateNewInvoiceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_BIENLAI.GET_ERR_INVOICES_TRY_AGAIN.
        /// </summary>
        internal static string Invoice_GetErrorInvoiceTryAgain {
            get {
                return ResourceManager.GetString("Invoice_GetErrorInvoiceTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_BIENLAI.GET_INDT_NAME_OF_INVOICES.
        /// </summary>
        internal static string Invoice_GetInvoiceDetailNames {
            get {
                return ResourceManager.GetString("Invoice_GetInvoiceDetailNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_BIENLAI.GET_INVOICES_SEND_MAIL.
        /// </summary>
        internal static string Invoice_GetInvoicesSendMail {
            get {
                return ResourceManager.GetString("Invoice_GetInvoicesSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_BIENLAI.HEADER_INVOICE.
        /// </summary>
        internal static string Invoice_InvoiceHeader {
            get {
                return ResourceManager.GetString("Invoice_InvoiceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_BIENLAI.SEARCH_INVOICES.
        /// </summary>
        internal static string Invoice_Search_Invoices {
            get {
                return ResourceManager.GetString("Invoice_Search_Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_BIENLAI.SET_FILE.
        /// </summary>
        internal static string Invoice_SetFile {
            get {
                return ResourceManager.GetString("Invoice_SetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_QUYETTOAN. GetLastInvoiceAudit.
        /// </summary>
        internal static string InvoiceAudit_GetLast {
            get {
                return ResourceManager.GetString("InvoiceAudit_GetLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_QUYETTOAN.SearchInvoiceAudit.
        /// </summary>
        internal static string InvoiceAudit_Search {
            get {
                return ResourceManager.GetString("InvoiceAudit_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_INVOICEPATTERN.GET_AND_CHECK_FOR_PUBLISHING.
        /// </summary>
        internal static string InvoicePattern_GetAndCheckForPublishing {
            get {
                return ResourceManager.GetString("InvoicePattern_GetAndCheckForPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_INVOICEPATTERN.Get_By_Invoice_Pattern_Id.
        /// </summary>
        internal static string InvoicePattern_GetByInvoicePatternId {
            get {
                return ResourceManager.GetString("InvoicePattern_GetByInvoicePatternId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_INVOICEPATTERN.GET_INVOICE_PATTERNS_ALLOWED.
        /// </summary>
        internal static string InvoicePattern_GetInvoicePatternsAllowed {
            get {
                return ResourceManager.GetString("InvoicePattern_GetInvoicePatternsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_BIENLAI.PAYMENT_METHOD_BY_ID.
        /// </summary>
        internal static string PaymentMethod_GetById {
            get {
                return ResourceManager.GetString("PaymentMethod_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_BIENLAI.GET_PAYMENT_METHODS.
        /// </summary>
        internal static string PaymentMethod_PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethod_PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_QUYEN.SETDEPARTMENTS.
        /// </summary>
        internal static string Permission_SetDepartments {
            get {
                return ResourceManager.GetString("Permission_SetDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_PUBLISHPATTERN.Get_List_By_PublishRelease_Id.
        /// </summary>
        internal static string PublishPattern_GetListByPublishReleaseId {
            get {
                return ResourceManager.GetString("PublishPattern_GetListByPublishReleaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_PUBLISHRELEASE.Get_By_Publish_Release_id.
        /// </summary>
        internal static string PublishRelease_GetByPublishReleaseId {
            get {
                return ResourceManager.GetString("PublishRelease_GetByPublishReleaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_PUBLISHRELEASE.SEARCH_PUBLISH_RELEASES.
        /// </summary>
        internal static string PublishRelease_SearchRelease {
            get {
                return ResourceManager.GetString("PublishRelease_SearchRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_REPORT.REPORT_DEPARTMENT.
        /// </summary>
        internal static string Report_InvoiceDepartment {
            get {
                return ResourceManager.GetString("Report_InvoiceDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_REPORT.REPORT_CHILDREN.
        /// </summary>
        internal static string Report_InvoiceDepartments {
            get {
                return ResourceManager.GetString("Report_InvoiceDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_REPORT.REPORT_MONTHS.
        /// </summary>
        internal static string Report_InvoiceMonths {
            get {
                return ResourceManager.GetString("Report_InvoiceMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_REPORT.REPORT_MONTHS_ONLY_DEPARTMENT.
        /// </summary>
        internal static string Report_InvoiceMonthsOnlyDepartment {
            get {
                return ResourceManager.GetString("Report_InvoiceMonthsOnlyDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_REPORT.REPORT_ONLY_DEPARTMENT.
        /// </summary>
        internal static string Report_InvoiceOnlyDepartment {
            get {
                return ResourceManager.GetString("Report_InvoiceOnlyDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_REPORT.REPORT_INVOICE_PATTERNS.
        /// </summary>
        internal static string Report_InvoicePatterns {
            get {
                return ResourceManager.GetString("Report_InvoicePatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLDT_DONVI.GET_SITEADMIN.
        /// </summary>
        internal static string SiteAdmin_GetByDepartmentId {
            get {
                return ResourceManager.GetString("SiteAdmin_GetByDepartmentId", resourceCulture);
            }
        }
    }
}
