//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Repositories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebClient.Repositories.QueryResource", typeof(QueryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_ACCOUNT.CHANGEPASSWORD.
        /// </summary>
        internal static string Account_ChangePassword {
            get {
                return ResourceManager.GetString("Account_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_ACCOUNT.GETACCOUNTBYCODE.
        /// </summary>
        internal static string Account_GetAccountByCode {
            get {
                return ResourceManager.GetString("Account_GetAccountByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_ACCOUNT.GETACCOUNTBYUSERNAME.
        /// </summary>
        internal static string Account_GetAccountByUsername {
            get {
                return ResourceManager.GetString("Account_GetAccountByUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_ACCOUNT.GETACCOUNTSBYEMPLOYEEID.
        /// </summary>
        internal static string Account_GetAccountsByEmployeeId {
            get {
                return ResourceManager.GetString("Account_GetAccountsByEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_ACCOUNT.GETALLACCOUNTSBYEMPLOYEEID.
        /// </summary>
        internal static string Account_GetAllAccountsByEmployeeId {
            get {
                return ResourceManager.GetString("Account_GetAllAccountsByEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_ACCOUNT.LOGIN.
        /// </summary>
        internal static string Account_Login {
            get {
                return ResourceManager.GetString("Account_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_NHANVIEN_QUYEN.GET_PERMISSIONIDS_OF_USER.
        /// </summary>
        internal static string AccPermission_GetPermissionIdsUser {
            get {
                return ResourceManager.GetString("AccPermission_GetPermissionIdsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_NHANVIEN_QUYEN.SET_PERMISSIONS.
        /// </summary>
        internal static string AccPermission_SetPermissions {
            get {
                return ResourceManager.GetString("AccPermission_SetPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_CHUONGTRINH.GETALL.
        /// </summary>
        internal static string App_GetAll {
            get {
                return ResourceManager.GetString("App_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_CHUONGTRINH.GETUSERAPPS.
        /// </summary>
        internal static string App_GetUserApps {
            get {
                return ResourceManager.GetString("App_GetUserApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_CHUONGTRINH.SETPERMISSION.
        /// </summary>
        internal static string App_SetPermission {
            get {
                return ResourceManager.GetString("App_SetPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_DONVI.GET_BY_ID.
        /// </summary>
        internal static string Department_Get_By_Id {
            get {
                return ResourceManager.GetString("Department_Get_By_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_DONVI.GETALLCHILDDEPARTMENTS.
        /// </summary>
        internal static string Department_GetAllChildDepartments {
            get {
                return ResourceManager.GetString("Department_GetAllChildDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_DONVI.GETALLDEPARTMENTSACCESSED.
        /// </summary>
        internal static string Department_GetAllDepartmentAccessed {
            get {
                return ResourceManager.GetString("Department_GetAllDepartmentAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_DONVI.GETCHILDNODES.
        /// </summary>
        internal static string Department_GetChildNodes {
            get {
                return ResourceManager.GetString("Department_GetChildNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_DONVI.INSERT_UNIT.
        /// </summary>
        internal static string Department_Insert {
            get {
                return ResourceManager.GetString("Department_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_DONVI.UPDATE_UNIT.
        /// </summary>
        internal static string Department_Update {
            get {
                return ResourceManager.GetString("Department_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_DONVI.UPDATEEMAIL.
        /// </summary>
        internal static string Department_UpdateEmail {
            get {
                return ResourceManager.GetString("Department_UpdateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_EMPLOYEE.DELETE_EMPLOYEE.
        /// </summary>
        internal static string Employee_DeleteById {
            get {
                return ResourceManager.GetString("Employee_DeleteById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_EMPLOYEE.GET_ALL_EMPLOYEE.
        /// </summary>
        internal static string Employee_Get_ALL {
            get {
                return ResourceManager.GetString("Employee_Get_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_EMPLOYEE.GET_EMPLOYEE_BY_DEPARTMENT_ID.
        /// </summary>
        internal static string Employee_Get_By_Department_Id {
            get {
                return ResourceManager.GetString("Employee_Get_By_Department_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_EMPLOYEE.GET_EMPLOYEE_BY_ID.
        /// </summary>
        internal static string Employee_Get_By_Id {
            get {
                return ResourceManager.GetString("Employee_Get_By_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_EMPLOYEE.INSERT_EMPLOYEE.
        /// </summary>
        internal static string Employee_Insert {
            get {
                return ResourceManager.GetString("Employee_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_EMPLOYEE.UPDATE_EMPLOYEE.
        /// </summary>
        internal static string Employee_Update {
            get {
                return ResourceManager.GetString("Employee_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.ADD_FEATURE.
        /// </summary>
        internal static string Feature_AddFeature {
            get {
                return ResourceManager.GetString("Feature_AddFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.FEATURE_NOTPERMISSION_ACCOUNT.
        /// </summary>
        internal static string Feature_FeatureNoPermissionAccount {
            get {
                return ResourceManager.GetString("Feature_FeatureNoPermissionAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.FEATURE_PERMISSION_ACCOUNT.
        /// </summary>
        internal static string Feature_FeaturePermissionAccount {
            get {
                return ResourceManager.GetString("Feature_FeaturePermissionAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.GET_MENU_FEATURES.
        /// </summary>
        internal static string Feature_Get_Menu_Feature {
            get {
                return ResourceManager.GetString("Feature_Get_Menu_Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.GET_ALL.
        /// </summary>
        internal static string Feature_GetAll {
            get {
                return ResourceManager.GetString("Feature_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.IS_ACCESSED_FEATURE.
        /// </summary>
        internal static string Feature_IsAccessedFeature {
            get {
                return ResourceManager.GetString("Feature_IsAccessedFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_FEATURE.UPDATE_FEATURE.
        /// </summary>
        internal static string Feature_UpdateFeature {
            get {
                return ResourceManager.GetString("Feature_UpdateFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_QUYEN.DELETE_QUYEN.
        /// </summary>
        internal static string Permission_DeletePermission {
            get {
                return ResourceManager.GetString("Permission_DeletePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_QUYEN.GET_PERMISSIONS.
        /// </summary>
        internal static string Permission_GetPermissions {
            get {
                return ResourceManager.GetString("Permission_GetPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN_QUYEN.SETDEPARTMENTS.
        /// </summary>
        internal static string Permission_SetDepartments {
            get {
                return ResourceManager.GetString("Permission_SetDepartments", resourceCulture);
            }
        }
    }
}
